In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as graph
import seaborn as sns

%load_ext line_profiler
%load_ext memory_profiler

In [2]:
# Instead of nested for loops

for i in range(1000):
    for j in range(1000):
        total = i+j

In [3]:
def sum_of_lists(N):
    total = 0
    for i in range(5):
        L = [j ^ (j >> i) for j in range(N)]
        total += sum(L)
    return total

In [4]:
%memit sum_of_lists(10)

peak memory: 112.91 MiB, increment: 0.18 MiB


# Introduction to Numpy

In [5]:
L = list(range(10))
print(L)
print(type(L))
print(f'One item in L is of type {type(L[8])}')

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
One item in L is of type <class 'int'>


In [6]:
# List of strings

c = [str(c) for c in L]
print(c)
print(type(c[1]))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
<class 'str'>


In [7]:
# List can be heterogenous

L = [1, 1.5, 'one', True]
print([type(c) for c in L])

[<class 'int'>, <class 'float'>, <class 'str'>, <class 'bool'>]


In [8]:
# Python fixed type arrays
import array

L = list(range(10))
a_L = array.array('i', L)
print(L, a_L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
# Python fixed type arrays

int_array = np.array(range(10))
float_array = np.array([1.5, 2, 3, 4, 5])
cast_float_array = np.array(range(10), dtype=float)

print(int_array)
print(float_array)
print(cast_float_array)

[0 1 2 3 4 5 6 7 8 9]
[1.5 2.  3.  4.  5. ]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
# nested numpy lists -> multi dimensional

print(np.array([range(i, i+3) for i in [1, 2, 3, 4]]))

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


#### Create Arrays from Scratch

In [11]:
# create array of zeros
print(np.zeros(10, dtype=int))

# create array of ones, with dimensions 2 * 5
print(np.ones((2, 5), dtype=float))

# create array of 5, with dimensions 3*5
print(np.full((3, 5), 5))

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
print(np.arange(0, 21, 2))

# Create an array of five values evenly spaced between 0 and 1
print(np.linspace(0, 1, 5))

# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
print(np.random.random((3, 3)))

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
print(np.random.normal(0, 1, (3, 3)))

# Create a 3x3 array of random integers in the interval [0, 10)
print(np.random.randint(0, 10, (3,3)))

# Create a 3x3 identity matrix
np.eye(3)

# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
print(np.empty(4))

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0.   0.25 0.5  0.75 1.  ]
[[0.52335333 0.92637292 0.13923124]
 [0.76208622 0.23492542 0.15402796]
 [0.28271583 0.51113969 0.76243607]]
[[-1.08501563 -0.32657954  0.77594246]
 [ 0.47827705  0.72122597 -0.39357841]
 [-1.41458088 -1.16261476  0.30099302]]
[[0 5 3]
 [7 1 0]
 [5 6 5]]
[0.25 0.5  0.75 1.  ]


## Basics of Numpy Arrays

In [27]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(2, 3))
x3 = np.random.randint(10, size=(2, 3, 4, 5))

print(x1)
print(x2)

print(f"x3 ndim: {x3.ndim}")
print(f"x3 shape: {x3.shape}")
print(f"x3 size: {x3.size}")
print(f'x3 dtype: {x3.dtype}')
print(f'x3 itemsize: {x3.itemsize} bytes')
print(f'x3 nbytes: {x3.nbytes} bytes')

[5 0 3 3 7 9]
[[3 5 2]
 [4 7 6]]
x3 ndim: 4
x3 shape: (2, 3, 4, 5)
x3 size: 120
x3 dtype: int64
x3 itemsize: 8 bytes
x3 nbytes: 960 bytes


In [57]:
x2 = np.random.randint(10, size=(2, 3))
print(x2)

# get 2nd row, 3rd column item
print(x2[1, 2])

# change 1st row, 2nd col to 0
x2[0, 1] = 0
print(x2)

[[3 2 0]
 [8 8 3]]
3
[[3 0 0]
 [8 8 3]]


In [47]:
# Slicing
# x[start:stop:step]

print(x3)
print(x3[:2, :2, :2])

[[[[8 8 1 6 7]
   [7 8 1 5 9]
   [8 9 4 3 0]
   [3 5 0 2 3]]

  [[8 1 3 3 3]
   [7 0 1 9 9]
   [0 4 7 3 2]
   [7 2 0 0 4]]

  [[5 5 6 8 4]
   [1 4 9 8 1]
   [1 7 9 9 3]
   [6 7 2 0 3]]]


 [[[5 9 4 4 6]
   [4 4 3 4 4]
   [8 4 3 7 5]
   [5 0 1 5 9]]

  [[3 0 5 0 1]
   [2 4 2 0 3]
   [2 0 7 5 9]
   [0 2 7 2 9]]

  [[2 3 3 2 3]
   [4 1 2 9 1]
   [4 6 8 2 3]
   [0 0 6 0 6]]]]
[[[[8 8 1 6 7]
   [7 8 1 5 9]]

  [[8 1 3 3 3]
   [7 0 1 9 9]]]


 [[[5 9 4 4 6]
   [4 4 3 4 4]]

  [[3 0 5 0 1]
   [2 4 2 0 3]]]]


In [53]:
print(x2)
#first row
print(x2[0, :])

#first column
print(x2[:, 0])

[[3 0 8]
 [8 8 2]]
[3 0 8]
[3 8]


In [60]:
# No copy Views

x2_2 = x2[:2, :2] # make a subarray of 2
print(x2_2)

# x2_2[0, 0] = 4
# print(x2) # The original is changed

# We can simply copy to avoid this change thing

x2_2 = x2[:2, :2].copy()
print(x2_2)

x2_2[0, 0] = 4
print(x2)

[[3 0]
 [8 8]]
[[3 0]
 [8 8]]
[[3 0 0]
 [8 8 3]]


In [67]:
# Reshaping arrays

x_shaped = np.arange(9).reshape((3,3))
print(x_shaped)

x = np.array([1, 2, 3])
print(x, x.shape)

# row vector via reshape
x.reshape((3, 1))
print(x, x.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 2 3] (3,)
[1 2 3] (3,)


In [72]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [73]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [89]:
# Concatenate arrays

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([1, 5, 6, 7,])
print(x, y ,z)
print(np.concatenate([x, y, z]))

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(grid, grid.shape)
print(np.concatenate([grid, grid]), np.concatenate([grid, grid]).shape)
print(np.concatenate([grid, grid], axis=1), np.concatenate([grid, grid], axis=1).shape)

# vstack and hstack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
print(np.vstack([x, grid]), np.vstack([x, grid]).shape)

# horizontallystack the arrays
y = np.array([[99],
              [99]])
print(np.hstack([grid, y]), np.hstack([grid, y]).shape)

[1 2 3] [3 2 1] [1 5 6 7]
[1 2 3 3 2 1 1 5 6 7]
[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] (4, 3)
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]] (2, 6)
[[1 2 3]
 [9 8 7]
 [6 5 4]] (3, 3)
[[ 9  8  7 99]
 [ 6  5  4 99]] (2, 4)


In [93]:
# Aarray ssplittin

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3, x4 = np.split(x, [3, 5, 7])
print(x1, x2, x3, x4)

grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
print('Vertical split: ', upper, lower)

left, right = np.hsplit(grid, [2])
print('Horizontal split: ', left, right)


[1 2 3] [99 99] [3 2] [1]
Vertical split:  [[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
Horizontal split:  [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [117]:
### Numpy UFuncs

x = np.arange(6)
print(f'x is {x}')
print("x // 2 =", x // 2)  # floor division
print("x % 2  = ", x % 2) # modulus

print(-(0.8*x + 4) ** 2) # can be in any order
print(f'add 2 is {np.add(2, x)}')
print(f'+ 2 is {2 + x}')

print(f'absolute of x is {np.abs(-x)}')

# trig functions

theta = np.linspace(0, np.pi, 3)

print("theta      = ", theta)
print("sin(theta) = ", np.around(np.sin(theta), decimals=2))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

# Exp and logs
print("---------------------------LOGS------------------------------")
x = np.arange(5)

print(f'log x is {np.log(x)}')
print(f' 3 power x is {np.power(3, x)}')

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x)) # Give more precise output
print("log(1 + x) =", np.log1p(x))

# Scipy special
from scipy import special
print('----------------------------SPECIALS------------------------')
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

# Specify outputs
print('----------------------------SPECify OUTPUT------------------------')
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

x is [0 1 2 3 4 5]
x // 2 = [0 0 1 1 2 2]
x % 2  =  [0 1 0 1 0 1]
[-16.   -23.04 -31.36 -40.96 -51.84 -64.  ]
add 2 is [2 3 4 5 6 7]
+ 2 is [2 3 4 5 6 7]
absolute of x is [0 1 2 3 4 5]
theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0. 1. 0.]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
---------------------------LOGS------------------------------
log x is [      -inf 0.         0.69314718 1.09861229 1.38629436]
 3 power x is [ 1  3  9 27 81]
exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]
----------------------------SPECIALS------------------------
gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


/home/arshad/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: RuntimeWarning: divide by zero encountered in log
