In [ ]:
enemy attack - self defense (if enemy attack > self defense). Otherwise, the defender doesn't lose his health.

In [19]:
# Taken from mission Army Battles

# Taken from mission The Warriors

class Warrior:
    health: int = 50
    is_alive: bool = True
    attack: int = 5

class Knight(Warrior):
    attack = 7     
    
class Defender(Warrior):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.health = 60
        self.attack = 3
        self.defense = 2

def fight(unit_1, unit_2):
    while unit_1.is_alive and unit_2.is_alive:
        if type(unit_2).__name__ == 'Defender':
            if unit_2.defense > unit_1.attack:
                unit_2.health = unit_2.health
            else:
                unit_2.health -= unit_1.attack + unit_2.defense
        else:
            unit_2.health -= unit_1.attack
       
        if unit_2.health <= 0:
            unit_2.is_alive = False
            return True
        
        if type(unit_1).__name__ == 'Defender':
            if unit_1.defense > unit_2.attack:
                unit_1.defense = unit_1.defense
            else:
                unit_1.health -= unit_2.attack + unit_1.defense
        else:
            unit_1.health -= unit_2.attack
       
        if unit_1.health <= 0:
            unit_1.is_alive = False
            return False
        
class Army():
    def __init__(self):
        self.list_of_warriors = []
        
    def add_units(self, unit, amount):
        for _ in range(amount):
            self.list_of_warriors.append(unit())
    
    def unit_death(self):
        self.list_of_warriors.pop()
    

class Battle():
    def fight(self, attacking, defending):
        
        while len(attacking.list_of_warriors) > 0:
            if fight(attacking.list_of_warriors[-1], defending.list_of_warriors[-1]):
                defending.unit_death()
                
            else:
                attacking.unit_death()
            
            if len(defending.list_of_warriors) == 0:
                return True
        return False


if __name__ == '__main__':
    #These "asserts" using only for self-checking and not necessary for auto-testing
    
    #fight tests
    chuck = Warrior()
    bruce = Warrior()
    carl = Knight()
    dave = Warrior()
    mark = Warrior()
    bob = Defender()
    mike = Knight()
    rog = Warrior()
    lancelot = Defender()

    assert fight(chuck, bruce) == True
    assert fight(dave, carl) == False
    assert chuck.is_alive == True
    assert bruce.is_alive == False
    assert carl.is_alive == True
    assert dave.is_alive == False
    assert fight(carl, mark) == False
    assert carl.is_alive == False
    assert fight(bob, mike) == False
    assert fight(lancelot, rog) == True

    #battle tests
    my_army = Army()
    my_army.add_units(Defender, 1)
    
    enemy_army = Army()
    enemy_army.add_units(Warrior, 2)

    army_3 = Army()
    army_3.add_units(Warrior, 1)
    army_3.add_units(Defender, 1)

    army_4 = Army()
    army_4.add_units(Warrior, 2)

    battle = Battle()

    assert battle.fight(my_army, enemy_army) == False
    assert battle.fight(army_3, army_4) == True
    print("Coding complete? Let's try tests!")


AssertionError: 

In [21]:
fight(lancelot, rog)

In [17]:
lancelot

In [64]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as graph

# Data API

In [32]:
X = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [33]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


### Chaining Transformations

In [34]:
dataset = dataset.repeat(3).batch(7)

for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [35]:
dataset = dataset.map(lambda x: x*2)

In [36]:
dataset = dataset.apply(tf.data.experimental.unbatch())

In [37]:
dataset = dataset.filter(lambda x: x < 10)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [38]:
for item in dataset.take(3):
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


### Shuffling the data

In [39]:
dataset = tf.data.Dataset.range(10).repeat(3)
dataset = dataset.shuffle(buffer_size=5, seed=42).batch(7)

for item in dataset:
    print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 9], shape=(7,), dtype=int64)
tf.Tensor([3 6], shape=(2,), dtype=int64)


# The TFRecord Format

In [43]:
with tf.io.TFRecordWriter('my_data.tfrecord') as f:
    f.write(b'This is the first record')
    f.write(b"And this is the second record")

In [44]:
filepaths = ['my_data.tfrecord']
dataset = tf.data.TFRecordDataset(filepaths)

for item in dataset:
    print(item)

tf.Tensor(b'This is the first record', shape=(), dtype=string)
tf.Tensor(b'And this is the second record', shape=(), dtype=string)


### Protocol Buffers

In [45]:
syntax = "proto3";
message BytesList { repeated bytes value = 1; }
message FloatList { repeated float value = 1 [packed = true]; }
message Int64List { repeated int64 value = 1 [packed = true]; }

SyntaxError: invalid syntax (<ipython-input-45-ced68d25f5a8>, line 2)

In [46]:
from tensorflow.train import BytesList, FloatList, Int64List
from tensorflow.train import Feature, Features, Example

person_example = Example(
    features=Features(
        feature={"name": Feature(bytes_list=BytesList(value=[b"Alice"])), 
                 "id": Feature(int64_list=Int64List(value=[123])), 
                 "emails": Feature(bytes_list=BytesList(value=[b"a@b.com", b"c@d.com"]))
}))

In [47]:
with tf.io.TFRecordWriter('my_contacts.tfrecord') as f:
    f.write(person_example.SerializeToString())

### Loading and parsing Examples

In [48]:
feature_description = {
"name": tf.io.FixedLenFeature([], tf.string, default_value=""),
"id": tf.io.FixedLenFeature([], tf.int64, default_value=0),
"emails": tf.io.VarLenFeature(tf.string),
}

In [49]:
for serialized_example in tf.data.TFRecordDataset(['my_contacts.tfrecord']):
    parsed_example = tf.io.parse_single_sequence_example(serialized_example, feature_description)

In [50]:
tf.sparse.to_dense(parsed_example['emails'], default_value=b'')

TypeError: tuple indices must be integers or slices, not str

In [56]:
dataset = tf.data.TFRecordDataset(['my_contacts.tfrecord']).batch(10)

for serialized_examples in dataset:
    parsed_examples = tf.io.parse_example(serialized_examples, feature_description)

In [57]:
parsed_examples

{'emails': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7f024c6402d0>,
 'id': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([123])>,
 'name': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Alice'], dtype=object)>}

### Handling lists of lists using the sequence example Protobuf

In [58]:
parsed_context, parsed_feature_lists = tf.io.parse_single_sequence_example(
    serialized_sequence_example, context_feature_descriptions,sequence_feature_descriptions)

parsed_content = tf.RaggedTensor.from_sparse(parsed_feature_lists["content"])

NameError: name 'serialized_sequence_example' is not defined

# The Features API

In [61]:
import os
import tarfile
import urllib.request

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    os.makedirs(housing_path, exist_ok=True)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()
    
fetch_housing_data()

In [65]:
def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path, "housing.csv")
    return pd.read_csv(csv_path)

In [66]:
housing = load_housing_data()
housing.head()

ImportError: cannot import name 'is_url' from 'pandas.io.common' (/home/arshad/miniconda3/lib/python3.7/site-packages/pandas/io/common.py)

   longitude  latitude  housing_median_age  total_rooms  ...  households  median_income  median_house_value  ocean_proximity
0    -122.23     37.88                41.0        880.0  ...       126.0         8.3252            452600.0         NEAR BAY
1    -122.22     37.86                21.0       7099.0  ...      1138.0         8.3014            358500.0         NEAR BAY
2    -122.24     37.85                52.0       1467.0  ...       177.0         7.2574            352100.0         NEAR BAY
3    -122.25     37.85                52.0       1274.0  ...       219.0         5.6431            341300.0         NEAR BAY
4    -122.25     37.85                52.0       1627.0  ...       259.0         3.8462            342200.0         NEAR BAY

[5 rows x 10 columns]

In [68]:
housing_median_age = tf.feature_column.numeric_column("housing_median_age")

In [70]:
ocean_prox_vocab = ['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN']
ocean_proximity = tf.feature_column.categorical_column_with_vocabulary_list(
"ocean_proximity", ocean_prox_vocab)

In [71]:
bucketized_age = tf.feature_column.bucketized_column(housing_median_age, boundaries=[-1., -0.5, 0., 0.5, 1.]) # age was scaled

age_and_ocean_proximity = tf.feature_column.crossed_column([bucketized_age, ocean_proximity], hash_bucket_size=100)

### 1 Hot encoder

In [72]:
ocean_proximity_one_hot = tf.feature_column.indicator_column(ocean_proximity)

In [73]:
ocean_proximity_one_hot

IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='ocean_proximity', vocabulary_list=('<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'), dtype=tf.string, default_value=-1, num_oov_buckets=0))

### Encoding Categorical Features using Embeddings

In [74]:
ocean_proximity_embed = tf.feature_column.embedding_column(ocean_proximity, dimension=2)
ocean_proximity_embed

EmbeddingColumn(categorical_column=VocabularyListCategoricalColumn(key='ocean_proximity', vocabulary_list=('<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'), dtype=tf.string, default_value=-1, num_oov_buckets=0), dimension=2, combiner='mean', initializer=<tensorflow.python.ops.init_ops.TruncatedNormal object at 0x7f024c7449d0>, ckpt_to_load_from=None, tensor_name_in_ckpt=None, max_norm=None, trainable=True, use_safe_embedding_lookup=True)

In [75]:
columns = [bucketized_age, ocean_proximity_embed, housing_median_age]
feature_descriptions = tf.feature_column.make_parse_example_spec(columns)

In [76]:
feature_descriptions

{'housing_median_age': FixedLenFeature(shape=(1,), dtype=tf.float32, default_value=None),
 'ocean_proximity': VarLenFeature(dtype=tf.string)}

In [77]:
def parse_examples(serialized_examples):
    examples = tf.io.parse_example(serialized_examples, feature_descriptions)
    targets = examples.pop("median_house_value") # separate the targets
    return examples, targets

In [78]:
batch_size = 32
dataset = tf.data.TFRecordDataset(["my_data_with_features.tfrecords"])
dataset = dataset.repeat().shuffle(10000).batch(batch_size).map(parse_examples)

KeyError: in user code:

    <ipython-input-77-2d863701b829>:3 parse_examples  *
        targets = examples.pop("median_house_value") # separate the targets

    KeyError: 'median_house_value'


### Using Feature Columns in Your Models

In [80]:
columns_without_target = columns[:-1]

model = keras.models.Sequential([
    keras.layers.DenseFeatures(feature_columns=columns_without_target), # This will convert every input to a dense represntation
    keras.layers.Dense(1)])

model.compile(loss='mse', optimizer='sgd', metrics=['accuracy'])

In [ ]:
steps_per_epoch = len(X_train) // batch_size
history = model.fit(dataset, steps_per_epoch=steps_per_epoch, epochs=5)

# TF Transform

In [82]:
import tensorflow_transform as tft

AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'