In [1]:
from tensorflow import keras
import tensorflow as tf

import matplotlib.pyplot as graph
import numpy as np
import seaborn as sns

# Using Tensorflow Like Numpy

### Tensor and Operations

In [6]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [7]:
t = tf.constant([[1., 2., 3.], 
                 [4., 5., 6.]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [8]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [11]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [13]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [14]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [15]:
t @ tf.transpose(t) # matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

### Tensors and NUmpy

In [17]:
a = np.array([2, 4, 5])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 4, 5])>

In [18]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [19]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 4, 16, 25])>

In [20]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

### Type Conversions

Tensorflow does not do type conversions automatically as they can significantly reduce performance

In [21]:
tf.constant(2) + tf.constant(40)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [22]:
t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

### Variables

Acts like a constant tensor, BUT can be modified in place using assign()

In [25]:
v = tf.Variable([[1, 2, 3], 
                 [4, 5, 6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [26]:
v.assign(2 * v)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [27]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2, 42,  6],
       [ 8, 10, 12]], dtype=int32)>

In [29]:
v[:, 2].assign([0, 1])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2, 42,  0],
       [ 8, 10,  1]], dtype=int32)>

In [30]:
v.scatter_nd_update(indices = [[0, 0], [1, 2]], updates = [100, 200])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[100,  42,   0],
       [  8,  10, 200]], dtype=int32)>

### Other Data Structures:
 - Sparse Tensors: contain mostly 0s
 - Tensor Arrays: list of tensors
     - All tensors they contain should have same shape and data type
 - Ragged Tensors: Static lists of lists of tensors
 - String Tensors: represrnt byte strings 

# Customizing Models and Training Algorithms

### Custom Loss Functions

In [211]:
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)

In [ ]:
model.compile(loss=huber_fn, optimizer="nadam")
model.fit(X_train, y_train, [...])

### Saving and Loading models with custom components

In [ ]:
model = keras.models.load_model("my_model_with_a_custom_loss.h5", custom_objects={"huber_fn": huber_fn})

### Custom Activation Functions, Initializers, Regularizers, and Constraints

# Tensorflow Functions and Graphs

In [2]:
def cube(x):
    return x ** 3

cube(tf.constant(2))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [4]:
tf_cube = tf.function(cube)
tf_cube(2)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [6]:
@tf.function
def tf_cube(x):
    return x ** 3

tf_cube.python_function(2)

8

In [17]:
# Taken from mission The Warriors    


if __name__ == '__main__':
    #These "asserts" using only for self-checking and not necessary for auto-testing

    chuck = Warrior()
    bruce = Warrior()
    carl = Knight()
    dave = Warrior()
    mark = Warrior()

    assert fight(chuck, bruce) == True
    assert fight(dave, carl) == False
    assert chuck.is_alive == True
    assert bruce.is_alive == False
    assert carl.is_alive == True
    assert dave.is_alive == False
    assert fight(carl, mark) == False
    assert carl.is_alive == False

    print("Coding complete? Let's try tests!")


if __name__ == '__main__':
    #These "asserts" using only for self-checking and not necessary for auto-testing
    
    #battle tests
    my_army = Army()
    my_army.add_units(Knight, 3)
    
    enemy_army = Army()
    enemy_army.add_units(Warrior, 3)

    army_3 = Army()
    army_3.add_units(Warrior, 20)
    army_3.add_units(Knight, 5)
    
    army_4 = Army()
    army_4.add_units(Warrior, 30)

    battle = Battle()

    assert battle.fight(my_army, enemy_army) == True
    assert battle.fight(army_3, army_4) == False
    print("Coding complete? Let's try tests!")


Coding complete? Let's try tests!
Coding complete? Let's try tests!


In [16]:
class Warrior:
    health: int = 50
    is_alive: bool = True
    attack: int = 5

class Knight(Warrior):
    attack = 7        

def fight(unit_1, unit_2):
    while unit_1.is_alive and unit_2.is_alive:
        unit_2.health -= unit_1.attack
        if unit_2.health <= 0:
            unit_2.is_alive = False
            return True
        
        unit_1.health -= unit_2.attack
        if unit_1.health <= 0:
            unit_1.is_alive = False
            return False
        
class Army():
    def __init__(self):
        self.list_of_warriors = []
        
    def add_units(self, unit, amount):
        for _ in range(amount):
            self.list_of_warriors.append(unit())
    
    def unit_death(self):
        self.list_of_warriors.pop()
    

class Battle():
    def fight(self, attacking, defending):
        
        while len(attacking.list_of_warriors) > 0:
            if fight(attacking.list_of_warriors[-1], defending.list_of_warriors[-1]):
                defending.unit_death()
                
            else:
                attacking.unit_death()
            
            if len(defending.list_of_warriors) == 0:
                return True
        return False

In [ ]:
class Army:
    def __init__(self):
        self.list_of_warriors = []

    def add_units(self, unit, amount):
        for _ in range(amount):
            self.list_of_warriors.append(unit())

    def unit_death(self):
        self.list_of_warriors.pop()


class Battle:
    def fight(self, attacking, defending):

        while len(attacking.list_of_warriors) > 0:

            if fight(attacking.list_of_warriors[-1], defending.list_of_warriors[-1]):
                defending.unit_death()
            else:
                attacking.unit_death()
            if len(defending.list_of_warriors) == 0:
                return True

        return False

In [14]:
my_army.list_of_warriors